### ISSUE TITLE
"Assertion failed" and "sendMessage timeout"

### ISSUE THREAD

**Issue by Bond246** [twocolors/node-red-contrib-esphome#26]
Hello,

i try to connect a new esphome project - my first project with esphome.
While i'm not using HA i tried MQTT but had a lot of reboots. The maintainer told me to try to disable mqtt and use the API instead.
Thats why i moved to this project.

But unfortunately i have much more issues with that flow in Node-RED.
First connection is fine but after a while it loses connection, i see a lot of reconnects on esp-side and get a lot of messages like:
```
"Assertion failed"
"sendMessage timeout"
```

My Node-RED is on latest version 3.1.0 with node.JS v18 on docker.

Is there anything that could be improved or better logs?

Thanks

**Comment by Bond246** [comment]
I don't use encryption or a password actually. Its all plain unencrypted traffic.

**Comment by twocolors** [comment]
hm, show me screen what you send to out-node

**Comment by Bond246** [comment]
> hm, show me screen what you send to out-node

nothing. It actually dont use the output-node. Thats the fun :)

**Comment by Bond246** [comment]
I'm in docker and normaly a ping is ~20ms.

**Comment by twocolors** [comment]
docker network like make ? use
```
    network_mode: host
```

**Comment by Bond246** [comment]
No, of course not.
All my smarthome services are in a user defined bridget network. Nothing else is needed.

**Comment by twocolors** [comment]
@Bond246 try new version, will show more info in error

**Comment by caitken-com** [comment]
I have the same errors. Editing the each config node without making any change but clicking 'update' (and deploy) usually fixes it: reconnects instantly and runs happily for another 24 hours or so, then errors again.

This time it failed to reconnect, and crashed NR completely.

Devices:

- [ESP32 dev board](https://www.amazon.com.au/dp/B086MJGFVV?th=1&ref_=as_li_ss_tl&language=en_US&linkCode=gs2&linkId=2c51ef973ca847bf15289e46ba64f89a&tag=digiblura-22)
- [HLK-LD1125H-24G Presence sensor](https://www.aliexpress.us/item/1005004149442851.html?aff_fcid=663ef4d37119420c94548c7fd05af3cf-1684937334494-09762-_DmoBDV3&tt=CPS_NORMAL&aff_fsk=_DmoBDV3&aff_platform=shareComponent-detail&sk=_DmoBDV3&aff_trace_key=663ef4d37119420c94548c7fd05af3cf-1684937334494-09762-_DmoBDV3&terminal_id=4de8e9265304491ebccae34aa23d7f73&afSmartRedirect=y&gatewayAdapt=4itemAdapt)

Yaml Config
- [LD1125H-Complete](https://github.com/patrick3399/Hi-Link_mmWave_Radar_ESPHome/blob/main/LD1125H/ESP32-LD1125H-Complete.yaml)

Crash logs:
```
30 Dec 18:04:41 - [error] [esphome-device:Rumpus-radar] sendMessage timeout waiting for DeviceInfoResponse
[NodeRed2 B323@Rumpus Occupancy Sensor@Rumpus Occupancy Sensor@Occupancy Detected] characteristic value expected valid finite number and received "NaN" (number)
30 Dec 18:05:47 - [error] [esphome-device:Rumpus-radar] sendMessage timeout waiting for DeviceInfoResponse
[NodeRed2 B323@Rumpus Occupancy Sensor@Rumpus Occupancy Sensor@Occupancy Detected] characteristic value expected valid finite number and received "NaN" (number)
30 Dec 18:05:50 - [red] Uncaught Exception:
30 Dec 18:05:50 - [error] Error: write after end
    at new NodeError (node:internal/errors:405:5)
    at _write (node:internal/streams/writable:322:11)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at PlaintextFrameHelper.sendMessage (/home/pi/.node-red/node_modules/@2colors/esphome-native-api/lib/utils/plaintextFrameHelper.js:70:21)
    at EsphomeNativeApiConnection.sendMessage (/home/pi/.node-red/node_modules/@2colors/esphome-native-api/lib/connection.js:179:26)
    at EsphomeNativeApiConnection.disconnect (/home/pi/.node-red/node_modules/@2colors/esphome-native-api/lib/connection.js:168:18)
    at EsphomeNativeApiClient.disconnect (/home/pi/.node-red/node_modules/@2colors/esphome-native-api/lib/client.js:84:25)
    at RED.nodes.registerType.credentials.encryptionkey.type.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-esphome/src/nodes/device.ts:167:21)
    at RED.nodes.registerType.credentials.encryptionkey.type.Node.close (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:340:26)
    at stopNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:745:31)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=20s expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 2.
```

**Comment by twocolors** [comment]
@caitken-com try node-red-contrib-esphome@0.2.6

**Comment by chibm** [comment]
I also encountered the same problem, and I think it may be caused by ESP32s, because my other projects, such as ESP8266, are running normally.
![image](https://github.com/twocolors/node-red-contrib-esphome/assets/67989598/86ebb78e-7686-48e0-a703-a53bfa038184)
![image](https://github.com/twocolors/node-red-contrib-esphome/assets/67989598/5d9bb148-2876-4a39-b4f6-3c9151893b87)

**Comment by twocolors** [comment]
hi enable in device reconnect and update to 0.2.8
